kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-rethinka
  spec:
    capacity:
      storage: 500Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/pv-rethinka
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-rethinkb
  spec:
    capacity:
      storage: 500Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/pv-rethinkb
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-rethinkc
  spec:
    capacity:
      storage: 500Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/pv-rethinkc
